#!/bin/bash


#Check prerequisites
command -v lftp >/dev/null 2>&1 || { echo >&2 "I require lftp but it's not installed.  Aborting."; exit 1; }
command -v lockfile >/dev/null 2>&1 || { echo >&2 "I require lockfile but it's not installed.  Aborting."; exit 1; }


#Load config files
CONFIG="$HOME/.rftp.conf"
if [ ! -r $CONFIG ]; then
  echo "Config file $CONFIG is missing!"
  exit 1
fi
source $CONFIG


#Start ftp sync
LOCKFILE="/tmp/rftp.lock"
lockfile -r 0 $LOCKFILE 2>/dev/null || exit 0

#Remove lockfile if lftp terminates unexpected
trap "echo 'ERROR: lftp interrupted'; rm -f $LOCKFILE; exit 1" SIGINT SIGTERM

lftp -u $login,$pass -p $port sftp://$host << EOF
set pget:default-n 5
set pget:save-status 30

set mirror:use-pget-n 5
set mirror:parallel-transfer-count 2
set mirror:parallel-directories true
set mirror:set-permissions false

set xfer:verify true

mirror --continue --verbose=1 $remote_dir $local_dir || echo "FAILED"
quit
EOF

rm -f $LOCKFILE
exit 0
